name: ps_books_workspace
publish_to: none

environment:
  sdk: ^3.11.0

dev_dependencies:
  melos: ^8.0.0

workspace:
  - app
  - packages/epub_pro
  - packages/dart_pdf_reader
  - packages/katbook_epub_reader
  - packages/comic_reader
  - packages/kindle_unpack
  - packages/unrar
  - packages/webview_all
  - packages/webview_all_linux
  - packages/webview_all_ohos
  - packages/webview_all_web
  - packages/webview_all_windows
  - packages/flutter_gen_ai_chat_ui
  - packages/flutter_download_manager

dependency_overrides:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  archive: ^4.0.7
  file_picker: ^10.3.10
  cli_util: ^0.4.2
  sqlparser: ^0.45.0
  analyzer: ^13.0.0
  dart_style: 3.1.9

melos:
  name: ps_books
