// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Packed(1)
final class RARHeaderData extends ffi.Struct {
  @ffi.Array.multi([260])
  external ffi.Array<ffi.Char> ArcName;

  @ffi.Array.multi([260])
  external ffi.Array<ffi.Char> FileName;

  @ffi.UnsignedInt()
  external int Flags;

  @ffi.UnsignedInt()
  external int PackSize;

  @ffi.UnsignedInt()
  external int UnpSize;

  @ffi.UnsignedInt()
  external int HostOS;

  @ffi.UnsignedInt()
  external int FileCRC;

  @ffi.UnsignedInt()
  external int FileTime;

  @ffi.UnsignedInt()
  external int UnpVer;

  @ffi.UnsignedInt()
  external int Method;

  @ffi.UnsignedInt()
  external int FileAttr;

  external ffi.Pointer<ffi.Char> CmtBuf;

  @ffi.UnsignedInt()
  external int CmtBufSize;

  @ffi.UnsignedInt()
  external int CmtSize;

  @ffi.UnsignedInt()
  external int CmtState;
}

final class RARHeaderDataEx extends ffi.Opaque {}

@ffi.Packed(1)
final class RAROpenArchiveData extends ffi.Struct {
  external ffi.Pointer<ffi.Char> ArcName;

  @ffi.UnsignedInt()
  external int OpenMode;

  @ffi.UnsignedInt()
  external int OpenResult;

  external ffi.Pointer<ffi.Char> CmtBuf;

  @ffi.UnsignedInt()
  external int CmtBufSize;

  @ffi.UnsignedInt()
  external int CmtSize;

  @ffi.UnsignedInt()
  external int CmtState;
}

typedef UNRARCALLBACKFunction =
    ffi.Int Function(
      ffi.UnsignedInt msg,
      ffi.Long UserData,
      ffi.Long P1,
      ffi.Long P2,
    );
typedef DartUNRARCALLBACKFunction =
    int Function(int msg, int UserData, int P1, int P2);
typedef UNRARCALLBACK = ffi.Pointer<ffi.NativeFunction<UNRARCALLBACKFunction>>;

final class RAROpenArchiveDataEx extends ffi.Opaque {}

enum UNRARCALLBACK_MESSAGES {
  UCM_CHANGEVOLUME(0),
  UCM_PROCESSDATA(1),
  UCM_NEEDPASSWORD(2),
  UCM_CHANGEVOLUMEW(3),
  UCM_NEEDPASSWORDW(4),
  UCM_LARGEDICT(5);

  final int value;
  const UNRARCALLBACK_MESSAGES(this.value);

  static UNRARCALLBACK_MESSAGES fromValue(int value) => switch (value) {
    0 => UCM_CHANGEVOLUME,
    1 => UCM_PROCESSDATA,
    2 => UCM_NEEDPASSWORD,
    3 => UCM_CHANGEVOLUMEW,
    4 => UCM_NEEDPASSWORDW,
    5 => UCM_LARGEDICT,
    _ => throw ArgumentError(
      'Unknown value for UNRARCALLBACK_MESSAGES: $value',
    ),
  };
}

typedef CHANGEVOLPROCFunction =
    ffi.Int Function(ffi.Pointer<ffi.Char> ArcName, ffi.Int Mode);
typedef DartCHANGEVOLPROCFunction =
    int Function(ffi.Pointer<ffi.Char> ArcName, int Mode);
typedef CHANGEVOLPROC = ffi.Pointer<ffi.NativeFunction<CHANGEVOLPROCFunction>>;
typedef PROCESSDATAPROCFunction =
    ffi.Int Function(ffi.Pointer<ffi.UnsignedChar> Addr, ffi.Int Size);
typedef DartPROCESSDATAPROCFunction =
    int Function(ffi.Pointer<ffi.UnsignedChar> Addr, int Size);
typedef PROCESSDATAPROC =
    ffi.Pointer<ffi.NativeFunction<PROCESSDATAPROCFunction>>;

const int ERAR_SUCCESS = 0;

const int ERAR_END_ARCHIVE = 10;

const int ERAR_NO_MEMORY = 11;

const int ERAR_BAD_DATA = 12;

const int ERAR_BAD_ARCHIVE = 13;

const int ERAR_UNKNOWN_FORMAT = 14;

const int ERAR_EOPEN = 15;

const int ERAR_ECREATE = 16;

const int ERAR_ECLOSE = 17;

const int ERAR_EREAD = 18;

const int ERAR_EWRITE = 19;

const int ERAR_SMALL_BUF = 20;

const int ERAR_UNKNOWN = 21;

const int ERAR_MISSING_PASSWORD = 22;

const int ERAR_EREFERENCE = 23;

const int ERAR_BAD_PASSWORD = 24;

const int ERAR_LARGE_DICT = 25;

const int RAR_OM_LIST = 0;

const int RAR_OM_EXTRACT = 1;

const int RAR_OM_LIST_INCSPLIT = 2;

const int RAR_SKIP = 0;

const int RAR_TEST = 1;

const int RAR_EXTRACT = 2;

const int RAR_VOL_ASK = 0;

const int RAR_VOL_NOTIFY = 1;

const int RAR_DLL_VERSION = 9;

const int RAR_HASH_NONE = 0;

const int RAR_HASH_CRC32 = 1;

const int RAR_HASH_BLAKE2 = 2;

const int RHDF_SPLITBEFORE = 1;

const int RHDF_SPLITAFTER = 2;

const int RHDF_ENCRYPTED = 4;

const int RHDF_SOLID = 16;

const int RHDF_DIRECTORY = 32;

const int ROADF_VOLUME = 1;

const int ROADF_COMMENT = 2;

const int ROADF_LOCK = 4;

const int ROADF_SOLID = 8;

const int ROADF_NEWNUMBERING = 16;

const int ROADF_SIGNED = 32;

const int ROADF_RECOVERY = 64;

const int ROADF_ENCHEADERS = 128;

const int ROADF_FIRSTVOLUME = 256;

const int ROADOF_KEEPBROKEN = 1;
